- name: Setting up Secret
  ansible.builtin.debug:
    msg: "name: {{ flux_secret.namespace }}/{{ flux_secret.name }}"

- name: Create Git Secret for FluxCD
  delegate_to: 'localhost'
  become: false
  ansible.builtin.shell: |
    export KUBECONFIG="{{ fluxcd_kubernetes.config_path }}"
    flux create secret git {{ flux_secret.name }} \
      --namespace {{ flux_secret.namespace }} \
      --url={{ flux_secret.url }} \
      --username={{ flux_secret.username }} \
      --password={{ flux_secret.password }}
  args:
    executable: /bin/bash
  when: "flux_secret.type == 'git'"
  register: bass_result
  changed_when: "bass_result.rc == 0"
  no_log: true

- name: Create Helm Secret for FluxCD
  delegate_to: 'localhost'
  become: false
  ansible.builtin.shell: |
    export KUBECONFIG="{{ fluxcd_kubernetes.config_path }}"
    flux create secret git {{ flux_secret.name }} \
      --namespace={{ flux_secret.namespace }} \
      --username={{ flux_secret.username }} \
      --password={{ flux_secret.password }}
  args:
    executable: /bin/bash
  when: "flux_secret.type == 'helm'"
  register: bass_result
  changed_when: "bass_result.rc == 0"
  no_log: true

- name: Create OCI Secret for FluxCD
  delegate_to: 'localhost'
  become: false
  ansible.builtin.shell: |
    export KUBECONFIG="{{ fluxcd_kubernetes.config_path }}"
    flux create secret oci {{ flux_secret.name }} \
      --namespace {{ flux_secret.namespace }} \
      --url={{ flux_secret.url }} \
      --username={{ flux_secret.username }} \
      --password={{ flux_secret.password }}
  args:
    executable: /bin/bash
  when: "flux_secret.type == 'oci'"
  register: bass_result
  changed_when: "bass_result.rc == 0"
  no_log: true
