- name: Create Generic Kubernetes Secret for FluxCD
  delegate_to: 'localhost'
  become: false
  ansible.builtin.shell: |
    export KUBECONFIG="{{ fluxcd_kubernetes.config_path }}"
    kubectl -n flux-system \
      create secret generic {{ flux_k8s_secret.name }} \
      --from-literal={{ flux_k8s_secret.value }}
  args:
    executable: /bin/bash
  register: bass_result
  changed_when: "bass_result.rc == 0"
  failed_when: "bass_result.rc == 1 and 'already exists' not in bass_result.stderr"
