---
# tasks file for secret

- name: Test before continue
  delegate_to: 'localhost'
  become: false
  ansible.builtin.shell: |
    export KUBECONFIG="{{ fluxcd_kubernetes.config_path }}"
    flux check
  args:
    executable: /bin/bash
  changed_when: false

- name: Create Secrets
  ansible.builtin.include_tasks: create_secret.yaml
  with_items: "{{ fluxcd_secrets }}"
  loop_control:
    loop_var: flux_secret
