---
# tasks file for secret

- name: Test before continue
  delegate_to: 'localhost'
  become: false
  ansible.builtin.shell: |
    export KUBECONFIG="{{ fluxcd_kubernetes.config_path }}"
    flux check
  args:
    executable: /bin/bash
  changed_when: false

- name: Create Flux Secrets
  ansible.builtin.include_tasks: create_flux_secret.yaml
  with_items: "{{ fluxcd_secrets }}"
  loop_control:
    loop_var: flux_secret

- name: Create k8s Opaque Secrets
  ansible.builtin.include_tasks: create_k8s_secret.yaml
  with_items: "{{ fluxcd_kubernetes_secrets }}"
  loop_control:
    loop_var: flux_k8s_secret
