namespace: mikejonesey
name: fluxcd
version: 1.2.0
readme: README.md
authors:
  - Michael Jones <mj@mikejonesey.co.uk>
description: Common mondane tasks when adding flux to another k8s env or swapping laptop.
license:
  - GPL-2.0-or-later
tags: ['flux', 'fluxcd', 'linux', 'tools']
dependencies: {}
repository: https://github.com/mikejonesey/ansible-collection-fluxcd
documentation: https://github.com/mikejonesey/ansible-collection-fluxcd/blob/main/README.md
homepage: https://github.com/mikejonesey/ansible-collection-fluxcd
issues: https://github.com/mikejonesey/ansible-collection-fluxcd/issues
build_ignore:
  - '.gitlab-ci.yml'
  - '.github/*'
