---
# defaults file for secret

fluxcd_kubernetes:
  config_path: "/home/{{ ansible_user }}/.kube/config"

# All the secrets created with flux
# ie git, helm, notation, oci, tls
fluxcd_secrets: {}

#  fluxcd_secrets:
#    - name: "example"
#      type: "git"
#      url: "gitlab.example.com"
#      username: "my-username"
#      password: "my-password"
#    - name: "other"
#      type: "helm"
#      namespace: "my-namespace"
#      username: "my-username"
#      password: "my-password"

# Extra secrets created with kubectl / k8s manifest
# eg for webhook-reciever, or alert-provider
fluxcd_kubernetes_secrets:
  - name: "webhook-token"
    value: "token={{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=28) | md5 }}"

#  fluxcd_kubernetes_secrets:
#    - name: "webhook-token"
#      value: "token=my-token"
#    - name: "slack-url"
#      value: "address=https://my-url"
#    - name: "discord-url"
#      value: "address=https://my-url"
