---
# defaults file for secret

fluxcd_kubernetes:
  config_path: "/home/{{ ansible_user }}/.kube/config"

fluxcd_secrets: {}

#  fluxcd_secrets:
#    - name: "example"
#      type: "git"
#      url: "gitlab.example.com"
#      username: "my-username"
#      password: "my-password"
#    - name: "other"
#      type: "helm"
#      namespace: "my-namespace"
#      username: "my-username"
#      password: "my-password"
