---
# defaults file for secret

fluxcd_kubernetes:
  config_path: "/home/{{ ansible_user }}/.kube/config"

# All the secrets created with flux
# ie git, helm, notation, oci, tls
fluxcd_secrets: {}

#  fluxcd_secrets:
#    - name: "example-git"
#      type: "git"
#      namespace: "flux-system"
#      url: "gitlab.example.com"
#      username: "my-username"
#      password: "{{ lookup('passwordstore', 'fluxcd/git directory={{ password_dir }} create=false overwrite=no')}}"
#    - name: "example-helm"
#      type: "helm"
#      namespace: "my-namespace"
#      username: "my-username"
#      password: "{{ lookup('passwordstore', 'fluxcd/helm directory={{ password_dir }} create=false overwrite=no')}}"
#    - name: "example-docker"
#      type: "oci"
#      namespace: "flux-system"
#      url: "my-url"
#      username: "my-username"
#      password: "{{ lookup('passwordstore', 'fluxcd/oci directory={{ password_dir }} create=false overwrite=no')}}"

# Extra secrets created with kubectl / k8s manifest
# eg for webhook-reciever, or alert-provider
fluxcd_kubernetes_secrets:
  - name: "webhook-token"
    namespace: "flux-system"
    value: "token={{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=28) | md5 }}"

#  fluxcd_kubernetes_secrets:
#    - name: "webhook-token"
#      namespace: "flux-system"
#      value: "token={{ lookup('passwordstore', 'fluxcd/webhook-token directory={{ password_dir }} create=true overwrite=no')|md5 }}"
#    - name: "slack-url"
#      namespace: "flux-system"
#      value: "address={{ lookup('passwordstore', 'fluxcd/provider-url-slack directory={{ password_dir }} create=false overwrite=no')}}"
#    - name: "discord-url"
#      namespace: "flux-system"
#      value: "address={{ lookup('passwordstore', 'fluxcd/provider-url-discord directory={{ password_dir }} create=false overwrite=no')}}"
